server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  datacenter: whatisdatacenter
  environment: whatisenvironment
  hostname: whatishostname
  instance:
    preferIpAddress: true
